version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - fads_volume:/workspace
    ports:
      - "3000:3000"
    command: /bin/bash

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123!

  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  fads_volume:
  mongodb_data: