version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached
    ports:
      - "5000:5000"
      - "3000:3000"
      - "27017:27017"
      - "1433:1433"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NODE_ENV=development
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    stdin_open: true
    tty: true

  # Serviços adicionais podem ser adicionados aqui
  # mongo:
  #   image: mongo:6.0
  #   ports:
  #     - "27017:27017"