version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspaces/fads:cached
    ports:
      - "5000:5000"  # .NET API
      - "3000:3000"  # Node.js
    depends_on:
      - sqlserver
      - mongodb

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin123!
      - MSSQL_PID=Developer
    volumes:
      - mssql-data:/var/opt/mssql

  mongodb:
    image: mongo:6.0  # Versão específica (mais estável)
    container_name: mongodb_server
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  mssql-data: